
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-05-10 09:42:46 by wuyang
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace T4ConsoleApplication.Entities
{	

	public class Article
    {
		
		/// <summary>
		/// 
		/// </summary>		
		public int ArticleId { get; set; }
		
		/// <summary>
		/// 标题
		/// </summary>		
		public string Title { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? ArticleTypeId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? ApproveStatus { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string ComeFrom { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? ClickCount { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Avatar { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? IsTop { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Content { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Summary { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string KeyName { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public short? LocationType { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public string Tag { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? CreateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public DateTime? UpdateDate { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? UserId { get; set; }
		
		/// <summary>
		/// 
		/// </summary>		
		public int? OperatorId { get; set; }
		 
      
    }
}

